### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by morgurth**
Created an entry for Ptolus Chaositech Artifacts and fixed the Ptolus Chaositech Bomb, Void to use "1d6+3" for the level, instead of "1d6+2". Also fixed the accidental removal of a space in the "Bomb, Docility" I introduced.

### CODE REVIEW

**Comment by mrkwnzl** [comment]
The chaositech artifacts are already in the Artifacts (Fantasy) compendium. The reason for the cyphers being divided into specific kinds, as opposed to all other compendia which only divide by genre, is that so that it’s easier to create rollable tables for them. The other items don’t have roll tables.

Does that make sense?

**Comment by morgurth** [comment]
Oh I get it. I wish there was a searchable way to see this in Foundry VTT.  There is a roll table for the Chaositech Artifacts though. It's on page 536. No big deal though. I'll take that section back out.

Are the Ptolus "spells" or I guess in Cypher System "abilities" listed? If not I'm going to make them for my own use.

I will tell you the only capitalizing the first letter of the item is making my OCD twitch. lol.

**Comment by mrkwnzl** [comment]
> I'll take that section back out.

In the meantime, I’ve already corrected the Void Bomb in my end, sorry about that. Was there anything else in here?

> Are the Ptolus "spells" or I guess in Cypher System "abilities" listed? If not I'm going to make them for my own use.

Those are in the Big List of All Abilities From Everywhere. Easier to search this way.

> I will tell you the only capitalizing the first letter of the item is making my OCD twitch. lol.

I followed the convention in the rulebooks for that. Only abilities seem to be capitalized title style.

**Comment by morgurth** [comment]
Thanks again. I see them now. So never mind my changes. :P

**Comment by mrkwnzl** [comment]
All right. Thanks for the keen eye! Keep it coming! I’ll publish an update in a few days, in case you find anything more!

**Pull request closed without merging**
